import { type PlanEditForm } from "~/libs/types/types.js";

const activitiesMockData: PlanEditForm = {
	days: [
		{
			dayNumber: 1,
			id: "day-1",
			tasks: [
				{
					completedAt: null,
					description: "Set a calm tone every day.",
					executionTimeType: "afternoon",
					id: 11,
					isCompleted: false,
					order: 1,
					planDayId: 1,
					title: "Start the day with guided meditation.",
				},
				{
					completedAt: null,
					description: "Practice gratitude in your journal.",
					executionTimeType: "afternoon",
					id: 12,
					isCompleted: false,
					order: 2,
					planDayId: 1,
					title: "Write down three things you are grateful for.",
				},
				{
					completedAt: null,
					description: "Focus on every bite and flavor.",
					executionTimeType: "afternoon",
					id: 13,
					isCompleted: false,
					order: 3,
					planDayId: 1,
					title: "Practice mindful eating at lunch.",
				},
				{
					completedAt: null,
					description: "Know what you want to achieve.",
					executionTimeType: "afternoon",
					id: 14,
					isCompleted: false,
					order: 4,
					planDayId: 1,
					title: "Set an intention for the week.",
				},
				{
					completedAt: null,
					description: "Spend one hour without screens.",
					executionTimeType: "afternoon",
					id: 15,
					isCompleted: false,
					order: 5,
					planDayId: 1,
					title: "Do a digital detox before bed.",
				},
			],
		},
		{
			dayNumber: 2,
			id: "day-2",
			tasks: [
				{
					completedAt: null,
					description: "Choose your favorite physical exercise.",
					executionTimeType: "afternoon",
					id: 21,
					isCompleted: false,
					order: 1,
					planDayId: 2,
					title: "Do 30 minutes of physical activity.",
				},
				{
					completedAt: null,
					description: "Start the day with good energy.",
					executionTimeType: "afternoon",
					id: 22,
					isCompleted: false,
					order: 2,
					planDayId: 2,
					title: "Prepare a healthy breakfast.",
				},
				{
					completedAt: null,
					description: "Hydration is essential for you.",
					executionTimeType: "afternoon",
					id: 23,
					isCompleted: false,
					order: 3,
					planDayId: 2,
					title: "Drink at least 8 glasses of water.",
				},
				{
					completedAt: null,
					description: "Improve your body flexibility.",
					executionTimeType: "afternoon",
					id: 24,
					isCompleted: false,
					order: 4,
					planDayId: 2,
					title: "Do a stretching routine.",
				},
				{
					completedAt: null,
					description: "Proper rest is very important.",
					executionTimeType: "afternoon",
					id: 25,
					isCompleted: false,
					order: 5,
					planDayId: 2,
					title: "Go to bed 30 minutes earlier.",
				},
			],
		},
		{
			dayNumber: 3,
			id: "day-3",
			tasks: [
				{
					completedAt: null,
					description: "Choose a subject that interests you.",
					executionTimeType: "afternoon",
					id: 31,
					isCompleted: false,
					order: 1,
					planDayId: 3,
					title: "Read a chapter of a book.",
				},
				{
					completedAt: null,
					description: "Learn something new on your commute.",
					executionTimeType: "afternoon",
					id: 32,
					isCompleted: false,
					order: 2,
					planDayId: 3,
					title: "Listen to an educational podcast today.",
				},
				{
					completedAt: null,
					description: "It can be a language or programming.",
					executionTimeType: "afternoon",
					id: 33,
					isCompleted: false,
					order: 3,
					planDayId: 3,
					title: "Learn a new skill online.",
				},
				{
					completedAt: null,
					description: "Explore a topic of your curiosity.",
					executionTimeType: "afternoon",
					id: 34,
					isCompleted: false,
					order: 4,
					planDayId: 3,
					title: "Watch an interesting documentary.",
				},
				{
					completedAt: null,
					description: "Reflect on your learning.",
					executionTimeType: "afternoon",
					id: 35,
					isCompleted: false,
					order: 5,
					planDayId: 3,
					title: "Write down one new thing you learned.",
				},
			],
		},
		{
			dayNumber: 4,
			id: "day-4",
			tasks: [
				{
					completedAt: null,
					description: "Listen without interrupting the other person.",
					executionTimeType: "afternoon",
					id: 41,
					isCompleted: false,
					order: 1,
					planDayId: 4,
					title: "Practice active listening today.",
				},
				{
					completedAt: null,
					description: "Keep your social bonds strong.",
					executionTimeType: "afternoon",
					id: 42,
					isCompleted: false,
					order: 2,
					planDayId: 4,
					title: "Connect with a friend or family member.",
				},
				{
					completedAt: null,
					description: "A small gesture can change a day.",
					executionTimeType: "afternoon",
					id: 43,
					isCompleted: false,
					order: 3,
					planDayId: 4,
					title: "Do a random act of kindness.",
				},
				{
					completedAt: null,
					description: "Identify what you felt and why.",
					executionTimeType: "afternoon",
					id: 44,
					isCompleted: false,
					order: 4,
					planDayId: 4,
					title: "Write about your emotions.",
				},
				{
					completedAt: null,
					description: "Strengthen your personal connections.",
					executionTimeType: "afternoon",
					id: 45,
					isCompleted: false,
					order: 5,
					planDayId: 4,
					title: "Express gratitude to a loved one.",
				},
			],
		},
		{
			dayNumber: 5,
			id: "day-5",
			tasks: [
				{
					completedAt: null,
					description: "It can be drawing, writing, or playing music.",
					executionTimeType: "afternoon",
					id: 51,
					isCompleted: false,
					order: 1,
					planDayId: 5,
					title: "Dedicate 30 minutes to a hobby.",
				},
				{
					completedAt: null,
					description: "A clean environment helps you focus.",
					executionTimeType: "afternoon",
					id: 52,
					isCompleted: false,
					order: 2,
					planDayId: 5,
					title: "Organize a small area of your home.",
				},
				{
					completedAt: null,
					description: "Think of something that relaxes you.",
					executionTimeType: "afternoon",
					id: 53,
					isCompleted: false,
					order: 3,
					planDayId: 5,
					title: "Plan an activity for the weekend.",
				},
				{
					completedAt: null,
					description: "Let the music take over you.",
					executionTimeType: "afternoon",
					id: 54,
					isCompleted: false,
					order: 4,
					planDayId: 5,
					title: "Listen to a playlist and dance.",
				},
				{
					completedAt: null,
					description: "Think about what you have achieved.",
					executionTimeType: "afternoon",
					id: 55,
					isCompleted: false,
					order: 5,
					planDayId: 5,
					title: "Reflect on your achievements today.",
				},
			],
		},
		{
			dayNumber: 6,
			id: "day-6",
			tasks: [
				{
					completedAt: null,
					description: "Go to a park or trail.",
					executionTimeType: "afternoon",
					id: 61,
					isCompleted: false,
					order: 1,
					planDayId: 6,
					title: "Spend an hour in nature.",
				},
				{
					completedAt: null,
					description: "Be present in a conversation with someone.",
					executionTimeType: "afternoon",
					id: 62,
					isCompleted: false,
					order: 2,
					planDayId: 6,
					title: "Have a conversation without your phone.",
				},
				{
					completedAt: null,
					description: "Cooking can be very relaxing.",
					executionTimeType: "afternoon",
					id: 63,
					isCompleted: false,
					order: 3,
					planDayId: 6,
					title: "Try a new recipe today.",
				},
				{
					completedAt: null,
					description: "It can be a museum or a café.",
					executionTimeType: "afternoon",
					id: 64,
					isCompleted: false,
					order: 4,
					planDayId: 6,
					title: "Visit a new place in the city.",
				},
				{
					completedAt: null,
					description: "Appreciate the little things around you.",
					executionTimeType: "afternoon",
					id: 65,
					isCompleted: false,
					order: 5,
					planDayId: 6,
					title: "Take photos of beautiful things.",
				},
			],
		},
		{
			dayNumber: 7,
			id: "day-7",
			tasks: [
				{
					completedAt: null,
					description: "See what worked and what didn’t.",
					executionTimeType: "afternoon",
					id: 71,
					isCompleted: false,
					order: 1,
					planDayId: 7,
					title: "Review the highlights of the week.",
				},
				{
					completedAt: null,
					description: "Set your focus for the coming days.",
					executionTimeType: "afternoon",
					id: 72,
					isCompleted: false,
					order: 2,
					planDayId: 7,
					title: "Plan 3 priorities for the week.",
				},
				{
					completedAt: null,
					description: "Make your daily routine easier.",
					executionTimeType: "afternoon",
					id: 73,
					isCompleted: false,
					order: 3,
					planDayId: 7,
					title: "Prepare healthy snacks for the days.",
				},
				{
					completedAt: null,
					description: "Start the week with everything organized.",
					executionTimeType: "afternoon",
					id: 74,
					isCompleted: false,
					order: 4,
					planDayId: 7,
					title: "Tidy up your space for the week.",
				},
				{
					completedAt: null,
					description: "It can be a bath or reading.",
					executionTimeType: "afternoon",
					id: 75,
					isCompleted: false,
					order: 5,
					planDayId: 7,
					title: "Do a relaxing activity today.",
				},
			],
		},
	],
	notes:
		"Be flexible and kind to yourself. Consistency is the key to everything!",
	startDate: "2024-01-01",
	theme: "COLOURFUL",
	title: "7-Day Mindfulness Challenge",
};

export { activitiesMockData };
