const ZERO = 0;
const ONE = 1;
const LAST_INDEX = -1;

const EDITOR_ROWS = 10;

const BASE_DIMENSIONS = {
	HEIGHT: 1123,
	WIDTH: 794,
};

export { BASE_DIMENSIONS, EDITOR_ROWS, LAST_INDEX, ONE, ZERO };
