const KILOBYTE = 1024;
const UPLOAD_MAX_FILE_SIZE_MB = 2;
const UPLOAD_MAX_FILE_SIZE_BYTES =
	UPLOAD_MAX_FILE_SIZE_MB * KILOBYTE * KILOBYTE;

export { UPLOAD_MAX_FILE_SIZE_BYTES, UPLOAD_MAX_FILE_SIZE_MB };
