const SLOW_INTERVAL_MS = 100;
const SLOW_INCREMENT_MAX = 0.2;
const SLOW_INCREMENT_DIVISOR = 20;

const FAST_INTERVAL_MS = 150;
const FAST_INCREMENT = 1.5;

const PROGRESS_MAX_SLOW = 90;
const PROGRESS_MIN = 1;
const PROGRESS_MAX = 100;

export {
	FAST_INCREMENT,
	FAST_INTERVAL_MS,
	PROGRESS_MAX,
	PROGRESS_MAX_SLOW,
	PROGRESS_MIN,
	SLOW_INCREMENT_DIVISOR,
	SLOW_INCREMENT_MAX,
	SLOW_INTERVAL_MS,
};
