const SLIDE_DURATION_MS = 500;
const SLIDE_INTERVAL_MS = 2000;

const SLIDE_START_INDEX = 0;
const SLIDE_INCREMENT = 1;

export {
	SLIDE_DURATION_MS,
	SLIDE_INCREMENT,
	SLIDE_INTERVAL_MS,
	SLIDE_START_INDEX,
};
