const UserValidationRule = {
	EMAIL_MAXIMUM_LENGTH: 71,
	EMAIL_MINIMUM_LENGTH: 5,
	NAME_MAXIMUM_LENGTH: 40,
	NAME_MINIMUM_LENGTH: 3,
	NON_EMPTY_STRING_MIN_LENGTH: 1,
	PASSWORD_MAXIMUM_LENGTH: 16,
	PASSWORD_MINIMUM_LENGTH: 6,
} as const;

export { UserValidationRule };
