const QUIZ_CONSTANTS = {
	FIRST_ANSWER_INDEX: 0,
	FIRST_QUESTION: 1,
	ZERO_QUESTIONS: 0,
} as const;

const PROGRESS_CONSTANTS = {
	FIRST_QUESTION: 1,
} as const;

const NAVIGATION_CONSTANTS = {
	FIRST_QUESTION: 1,
} as const;

export { NAVIGATION_CONSTANTS, PROGRESS_CONSTANTS, QUIZ_CONSTANTS };
