const EDITOR_ROWS = 10;
const LAST_INDEX = -1;
const DEFAULT_PIXEL_RATIO = 1;
const DEFAULT_HEIGHT = 1080;
const DEFAULT_WIDTH = 1920;

const BASE_DIMENSIONS = {
	HEIGHT: 1123,
	WIDTH: 794,
};

export {
	BASE_DIMENSIONS,
	DEFAULT_HEIGHT,
	DEFAULT_PIXEL_RATIO,
	DEFAULT_WIDTH,
	EDITOR_ROWS,
	LAST_INDEX,
};
